# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-14 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(default='no_tweet_available', verbose_name='Maplecroft Tweet Content')),
                ('country_lat', models.TextField(default='', verbose_name='Country Latitude')),
                ('country_lon', models.TextField(default='', verbose_name='Country Longtitude')),
                ('published_at', models.DateTimeField(verbose_name='Published At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Maplecroft Tweet',
                'verbose_name_plural': 'Maplecroft Tweets',
            },
        ),
    ]
